version: 0.1

echo "hello from buildspec.yml"
phases:
  build:
    commands:
      - echo Build completed on `date`
      - mvn package

artifacts:
  files:     
   - 'target/quoteapp-0.0.1-SNAPSHOT.war'
